### ISSUE TITLE
Issue #1: Customize the design of the core team

### ISSUE THREAD

**Issue by arjunvuppala123** [acmpesuecc/acmpesuecc.github.io#25]
In the website, the details under the Core team heading  is taking a lot of space in the website. The requirement is that the Details of the Core team must take up the least space possible in the website. The name of the website file is index.html and its styling file is style.css. The sample output is attached with this issue.
![image](https://user-images.githubusercontent.com/56397988/96978941-952e6980-153c-11eb-9309-36518ef7b602.png)
NB:
1)this is just a sample output. It could be up to you how to resolve the issue.
2)Do not copy the sample output. if so, the modification will not be approved

**Comment by ShreyaPanale** [comment]
Hey, I would like to take this

**Comment by arjunvuppala123** [comment]
yes you can work on this!!
