### ISSUE TITLE
Issue #2: Modify the font style and size in the website

### ISSUE THREAD

**Issue by arjunvuppala123** [acmpesuecc/acmpesuecc.github.io#26]
You are to modify the font style and font-size appropriately in the website. This is to be done with the aim of making the website more stylish and unique.The name of the website file is index.html and its styling file is style.css.
Sample output:
![image](https://user-images.githubusercontent.com/56397988/96986042-b5f7be80-153e-11eb-9e79-d66062e15b85.png)
NB:
1)this is just a sample output. It could be upto you how to resolve the issue.
2)Do not copy the sample output. if so, the modification will not be approved
3)The styles has to applied wherever necessary in the website

**Comment by sidram05** [comment]
Would like to work  on this!

**Comment by arjunvuppala123** [comment]
best of luck!

**Comment by kkumuda** [comment]
hey can i work on this?

**Comment by arjunvuppala123** [comment]
yes sure you can work on this

**Comment by nishsm** [comment]
hi can i please work on this?

**Comment by arjunvuppala123** [comment]
yea sure go ahead
