### ISSUE TITLE
Issue #3: The size of event cards are not uniform

### ISSUE THREAD

**Issue by arjunvuppala123** [acmpesuecc/acmpesuecc.github.io#27]
The size of event card component is not uniform. You are to modify the sizes of all the event card such that the event cards are uniform.The name of the website file is index.html and its styling file is style.css.The name of the website file is index.html and its styling file is style.css.
Sample output:
![image](https://user-images.githubusercontent.com/56397988/96987347-834ec580-1540-11eb-874c-f33c8c5ed73f.png)

![image](https://user-images.githubusercontent.com/56397988/96987373-8ba70080-1540-11eb-83c6-497851eaa2e5.png)

NB:
1)this is just a sample output. It could be upto you how to resolve the issue.
2)Do not copy the sample output. if so, the modification will not be approved

**Comment by kkumuda** [comment]
can i try this?

**Comment by arjunvuppala123** [comment]
yes sure!! proceed :)

**Comment by ShreyaPanale** [comment]
Hey, I would like to do this

**Comment by arjunvuppala123** [comment]
yea sure go ahead!!
