### ISSUE TITLE
Issue #4: Customize the design of the founders

### ISSUE THREAD

**Issue by arjunvuppala123** [acmpesuecc/acmpesuecc.github.io#28]
In the website, the details under the Founders heading is taking a lot of space in the website. The requirement is that the Details of the Founders must take up the least space possible in the website. The sample output is attached with this issue.The name of the website file is index.html and its styling file is style.css.
![image](https://user-images.githubusercontent.com/56397988/97067071-8779f200-15d7-11eb-8091-3ab0bf953a55.png)
NB:
1)this is just a sample output. It could be up to you how to resolve the issue.
2)Do not copy the sample output. if so, the modification will not be approved

**Comment by ShreyaPanale** [comment]
Hey, I would like to take this

**Comment by arjunvuppala123** [comment]
yes you can work on this!!
