### ISSUE TITLE
Issue #5: Modify the positions of the social media icons

### ISSUE THREAD

**Issue by arjunvuppala123** [acmpesuecc/acmpesuecc.github.io#29]
In the footer of the website, The social media icons seemed to be cramped. These icons are to be position such that it should not cramped at one spot.The name of the website file is index.html and its styling file is style.css. Sample output:
![image](https://user-images.githubusercontent.com/56397988/97067281-6ca87d00-15d9-11eb-8f47-3cd1b2d69b37.png)
NB:
1)this is just a sample output. It could be up to you how to resolve the issue.
2)Do not copy the sample output. if so, the modification will not be approved

**Comment by sidram05** [comment]
Would like to work on this, thanks!

**Comment by arjunvuppala123** [comment]
best of luck!

**Comment by nishsm** [comment]
Would like to contribute

**Comment by srujandeshpande** [comment]
Go ahead
