### ISSUE TITLE
Issue #6: Modify styling of Faculty Sponsor's Description

### ISSUE THREAD

**Issue by arjunvuppala123** [acmpesuecc/acmpesuecc.github.io#30]
The description of Faculty Sponsor must not be cramped and must be styled appropriately. The name of the website file is index.html and its styling file is style.css.
Sample Output:
![image](https://user-images.githubusercontent.com/56397988/97067713-ea6e8780-15dd-11eb-9b87-ddbe69074eff.png)
NB:
1)this is just a sample output. It could be up to you how to resolve the issue.
2)Do not copy the sample output. if so, the modification will not be approved

**Comment by AmeyaPhadnis-2019H1030012G** [comment]
@arjunvuppala123 ,Can i give it a try, I am new to the open-source community and looking forward to opportunities to contribute.

**Comment by arjunvuppala123** [comment]
yes sure!! You can try!! All the best :-) !!!

**Comment by ShreyaPanale** [comment]
Hey, can you assign this to me
