### ISSUE TITLE
Issue #7: Documentation of the website

### ISSUE THREAD

**Issue by arjunvuppala123** [acmpesuecc/acmpesuecc.github.io#31]
Please create a file for the website so that it helps all the members to work on it with ease.
For a headstart , refer to this link as to how to provide a documentation for a website:
https://medium.com/@t1tan1um/generic-guide-for-documenting-web-projects-4d6110557e4b
NB:
1)this is for reference. It could be up to you how to resolve the issue.

**Comment by RakshithRAcharya** [comment]
Can you give the details of developers and maintainers for this website

**Comment by arjunvuppala123** [comment]
@RakshithRAcharya 
Maintainers :
arjunvuppala
Developers:
arjunvuppala
Hemant Sathish
Akhil Khubchandani
Chaitanya

**Comment by pallaviiprabhu** [comment]
@arjunvuppala123 Can I still take this up?
I'll have to create a new file, am I right?

**Comment by arjunvuppala123** [comment]
yes sure go ahead 
yes you need to create a new file
