### ISSUE TITLE
Refactor Codebase

### ISSUE THREAD

**Issue by srujandeshpande** [acmpesuecc/acmpesuecc.github.io#35]
All the files for different events should be in 1 folder called "events". 
Make sure you update the corresponding hyperlinks, css and js and well.

**Comment by ShreyaPanale** [comment]
I will try doing this!

**Comment by nishsm** [comment]
hi i would like to contribute to this

**Comment by srujandeshpande** [comment]
Go ahead! @nishsm

**Comment by abhishek-pes** [comment]
@arjunvuppala123 can I help with this

**Comment by arjunvuppala123** [comment]
yea go ahead :)
