### ISSUE TITLE
[BUG]Tensor flow event

### ISSUE THREAD

**Issue by nishsm** [acmpesuecc/acmpesuecc.github.io#39]
**Describe the bug**
In the events division , the tensor flow "READ MORE" button has not been linked to a valid website
(has been linked to tensorflow.ml)
hence goes to Secure Connection Failed page

**To Reproduce**
1. Go to 'ACM website'
2. Scroll down to 'Tensor flow' under 'Events'
3. Click on 'READ MORE'

**Expected behavior**
has to go to valid Tensorflow event page
**Screenshots**
![image](https://user-images.githubusercontent.com/56448813/97083160-f5500900-162b-11eb-9fbd-92034cd3fbdc.png)

**Desktop (please complete the following information):**
 - OS:Windows 10
 - Browser :Mozilla Firefox

**Comment by srujandeshpande** [comment]
Anyone is free to work on this. You can replace the link with https://acmpesuecc.github.io/Tensor-website/

**Comment by ShreyaPanale** [comment]
I will fix it :P

**Comment by arjunvuppala123** [comment]
yea sure !!
